### ISSUE TITLE
Questions about "Designing my life's System" blog post

### ISSUE THREAD

**Issue by m98** [imteekay/iamtk.co#1]
Hey TK!
I read the "[Designing my life's System](https://www.iamtk.co/designing-my-lifes-system)" blog post. It was very well written, and I  had good learnings from it. 

There are three questions that I would like to ask:

1. What is the Personal Knowledge Base you discussed in the article? Any specific tool or method you use for that?
2. You wrote the blog post on 2020. Do you still use the same approach? What are your recent learnings?
3. How did you realize that spirituality is essential to your "ever-improving" mindset? How do you differentiate between spirituality and mental health?

Thanks for sharing your experience and knowledge.

**Comment by imteekay** [comment]
Hey @m98, for the questions.
These are my insights: I hope to answer everything and help any other people who have the same questions.

---

### What is the Personal Knowledge Base that TK talked about in the article? Any specific tool or method he uses for that?

It's basically the intersection of a Notion page and my github repositories. The notion page is a directory of all "Learning Paths" I have created for myself to keep learning (see video). The github repositories are experiments and in-depth research.

https://user-images.githubusercontent.com/5835798/186732691-cd5fac97-1109-4bd2-86db-94aef22134e0.mov

And the github repositories are all here: https://github.com/imteekay

### TK wrote the blog in 2020. Does he still use the same method? What are his recent learnings?

Most of the things are still the same or very similar. I think I'm just more mature and I feel I keep improving, so most of the things I feel it's easier to do now.

-  `Health`: I've been focusing a lot on my health habits like running and eating better. I am even sleeping better, even though it could be improved for sure.
- `Habits`: I keep track of my habits on a daily basis and this is good to make sure I'm doing the things I really want to do or things I feel I need to do to improve my life
- `Goals`: I set some long term goals and I'm trying to match my actions and habits towards these goals.
- `Learning`: more in-depth research ([frontend infra](https://github.com/imteekay/frontend-infrastructure), [webperf](https://github.com/imteekay/web-performance-research), [programming language theory](https://github.com/imteekay/programming-language-research)), fundamentals ([algorithms](https://github.com/imteekay/algorithms), [frontend](https://github.com/imteekay/frontend)), and keep doing things I like to do

### How did he realize that spirituality is essential for him in his "ever- improving" mindset? For him, how did mental health and spirituality become different? (Some people consider that one thing!)

I see mental health more in the topics like stress, mindset, mental issues, mental clarity. And spirituality more in the topics like meaning of life, life purpose (and also religion — even though I was born and raised as a buddhist I never felt like a religious person — and this is totally personal).

It's difficult to really define those topics but I see them differently but having a lot of intersection in my life.

I'm always in search for the purpose of my life. Maybe it's a strong word but after reflecting about it, it always come down to [Knowledge Sharing & Education](https://www.iamtk.co/microblog/knowledge-sharing-and-education), [Intellectual Freedom](https://www.iamtk.co/microblog/intellectual-freedom), and [Independent Research and Freedom](https://www.iamtk.co/microblog/independent-research-and-freedom). Freedom and knowledge always show up in my self reflections and I try to keep my focus on it.

---

I hope this helps! Cheers ✌️
