### ISSUE TITLE
Jekyll Theme

### ISSUE THREAD

**Issue by gebeto** [imteekay/iamtk.co#6]
Yo!) I wrote you in LinkEdIn but there is no reaction :)

Can I make an jekyll theme from your website? It allows you to write your articles using `markdown` and it will generate google analytics, seo etc.
What you think a bout it? May I make it? (And use MIT license for it)

**Comment by leandrotk** [comment]
Hi @gebeto, actually it is not my template, I used the same as [this](https://fhinkel.rocks/about/) and [this](https://ericdouglas.github.io/) blogs.

I don't know the template actual name tbh.

If it was mine, I would let you make the jeykll theme for sure.

**Comment by gebeto** [comment]
Great! Thank you!)
